import { musicApi, Song } from '@/services/musicApi';
import { tmdbApi, Movie as TMDBMovie } from '@/services/tmdbApi';
import { MovieHero } from '@/components/MovieHero';
import { MovieRow } from '@/components/MovieRow';
import { CustomWatchParty } from '@/components/CustomWatchParty';
import { Search, X, Users, Sparkles } from 'lucide-react';
import { Input } from '@/components/ui/input';
import { Skeleton } from '@/components/ui/skeleton';
import { useNavigate } from 'react-router-dom';
import { toast } from 'sonner';
import { useMusic } from '@/context/MusicContext';