// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://hspvaszrwbagmaygyjtj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhzcHZhc3pyd2JhZ21heWd5anRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4Mjk0NTksImV4cCI6MjA3MDQwNTQ1OX0.bKgrISjHzm80IeAYJ4sUTsZDtnyNM6F9w7Djz6IJYG8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);