// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://aidjrytwdvhwgfjgkxyb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFpZGpyeXR3ZHZod2dmamdreHliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA3NTQxMzEsImV4cCI6MjA5NjMzMDEzMX0.fenwmwl6HaWEXZFGk2OMUnXROSFEe_NYYJwjwLOSA_o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);